[package]
name = "mary"
version = "0.2.0"
edition = "2021"
default-run = "mary"

[features]
test_with_roms = []

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
lexgen = "0.15"
lexgen_util = "0.15"
pomelo = "0.1"
thiserror = "1"
